linuxmint/cinnamon-settings-daemon

- plugins/media-keys/csd-media-keys-manager.c
because g_shell_parse_argv might return FALSE...
> avoid deferencing NULL pointer

- plugins/sound/csd-sound-manager.c
`org.cinnamon.SettingsDaemon.Sound`: new DBus method `PlaySoundFileVolume`, which is basically like `PlaySoundFile`, but needs has got an extra argument volume (string, decibel value)
>  new DBus method PlaySoundFileVolume

- plugins/xrandr/csd-xrandr-manager.c
Based on 
https://git.gnome.org/browse/gnome-settings-daemon/patch/plugins?id=92b5f78720c788e730d17b40f5ec52e129aa8bee
To fix
(cinnamon-settings-daemon:1642): CinnamonDesktop-CRITICAL **: gnome_rr_config_set_clone: assertion 'GNOME_IS_RR_CONFIG (self)' failed
> xrandr: Don't operate on a NULL object

- plugins/power/csd-power-manager.c
`org.cinnamon.SettingsDaemon.Power.Keyboard`: add methods `GetPercentage` and `SetPercentage`, like for `org.cinnamon.SettingsDaemon.Power.Screen` and a `Changed` signal.
**WARNING: Both methods are untested**
> Get- / SetPercentage for keyboard brightness

- plugins/media-keys/csd-media-keys-manager.c
Error when trying to use keyboard shortcut
```
'org.cinnamon.desktop.session' does not contain a key named 'button-suspend'
```
> Fix broken KB shortcuts for suspend, hibernate and shutdown

- plugins/print-notifications/csd-print-notifications-manager.c
When printing to a network printer use any of the ipp, lpd, socket, or dnssd backends, the cups-waiting-for-job-completed job state reason is normal and should not cause a desktop notification.
https://bugzilla.redhat.com/show_bug.cgi?id=1207154
> print-notifications: Don't show error for job in progress

- plugins/xsettings/csd-xsettings-manager.c
On newer laptops like the X1 Carbon the height is 1440, so it automatically does 2x HiDPI scaling. This isn't a great user experience out of the box, the text is bloated and menus are too large. Instead it should default to 1x scaling.
> Change the minimum height required to trigger HiDPI scaling.

- plugins/power/csd-power-manager.c
It's not enough to monitor state and warning-level.
Fixes issue #111.
> power: refresh device if any properties changed

- cinnamon-settings-daemon/cinnamon-settings-manager.c
local static function contained() can also go with a newer glib
> remove deprecated g_settings_list_schemas

- plugins/background/csd-background-manager.c
this is now hardcoded to return 1, so loops using this can be removed
> remove deprecated gdk_display_get_n_screens

- plugins/cursor/csd-cursor-manager.c
this only returns 1 now, so loops can be removed.
> remove deprecated function gdk_display_get_n_screens

- plugins/xsettings/csd-xsettings-manager.c
Apps like firefox, thunderbird  ignore cursor-size changes, this pull request fixes the issue
based on
https://git.gnome.org/browse/gnome-settings-daemon/commit/?id=d4a833907f5ef0ef1e59b69faafb60293cc191d2
> xsettings: Fix cursor-size changes being ignored

- autogen.sh
- cinnamon-settings-daemon/Makefile.am
- configure.ac
- debian/control
- plugins/a11y-keyboard/Makefile.am
- plugins/a11y-settings/Makefile.am
- plugins/automount/Makefile.am
- plugins/background/Makefile.am
- plugins/clipboard/Makefile.am
- plugins/color/Makefile.am
- plugins/common/Makefile.am
- plugins/cursor/Makefile.am
- plugins/datetime/Makefile.am
- plugins/dummy/Makefile.am
- plugins/housekeeping/Makefile.am
- plugins/keyboard/Makefile.am
- plugins/media-keys/Makefile.am
- plugins/mouse/Makefile.am
- plugins/orientation/Makefile.am
- plugins/power/Makefile.am
- plugins/print-notifications/Makefile.am
- plugins/screensaver-proxy/Makefile.am
- plugins/smartcard/Makefile.am
- plugins/sound/Makefile.am
- plugins/wacom/Makefile.am
- plugins/xrandr/Makefile.am
- plugins/xsettings/Makefile.am
gnome-common is deprecating some vars and macros, listed here:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=829932
This change follows the gnome recommendations from:
https://wiki.gnome.org/Projects/GnomeCommon/Migration
> Migrate away from gnome-common deprecated vars and macros

- plugins/mouse/csd-mouse-manager.c
The code was handling touchpad "left-handed" key as a boolean, but it's an enum.
backported from:
https://git.gnome.org/browse/gnome-settings-daemon/commit/?id=e52d2c20652624d386a7ff0919dcedd04055668d
> mouse: Fix critical warnings with touchpad settings

- plugins/media-keys/csd-media-keys-manager.c
Based on
https://github.com/GNOME/gnome-settings-daemon/commit/76b548e3dd4c52455e9c2684d2e64e41b9c5cd84
needs this commit to compile
https://github.com/linuxmint/cinnamon-desktop/pull/83
> media-keys: Add Rotation lock support

- plugins/power/csd-power-manager.c
Based on https://git.gnome.org/browse/gnome-settings-daemon/patch/?id=3c13c9efcadbbd465b1396429209cbd0105bb6a7
From 3c13c9efcadbbd465b1396429209cbd0105bb6a7 Mon Sep 17 00:00:00 2001
From: Hans de Goede <hdegoede@redhat.com>
Date: Fri, 14 Oct 2016 18:07:17 +0200
Subject: power: Fix typo in UPower keyboard GDBus proxy name
s/upower_kdb_proxy/upower_kbd_proxy/
https://bugzilla.gnome.org/show_bug.cgi?id=773402
> power: Fix typo in UPower keyboard GDBus proxy name

- plugins/a11y-keyboard/csd-a11y-keyboard-manager.c
- plugins/a11y-keyboard/csd-a11y-preferences-dialog.c
- plugins/automount/csd-automount-manager.c
- plugins/background/csd-background-manager.c
- plugins/clipboard/csd-clipboard-manager.c
- plugins/color/csd-color-manager.c
- plugins/cursor/csd-cursor-manager.c
- plugins/dummy/csd-dummy-manager.c
- plugins/housekeeping/csd-housekeeping-manager.c
- plugins/housekeeping/csd-ldsm-dialog.c
- plugins/keyboard/csd-keyboard-manager.c
- plugins/media-keys/csd-media-keys-manager.c
- plugins/mouse/csd-mouse-manager.c
- plugins/orientation/csd-orientation-manager.c
- plugins/power/csd-power-manager.c
- plugins/print-notifications/csd-print-notifications-manager.c
- plugins/screensaver-proxy/csd-screensaver-proxy-manager.c
- plugins/sound/csd-sound-manager.c
- plugins/xrandr/csd-xrandr-manager.c
- plugins/xsettings/csd-xsettings-manager.c
Fixes 70 warnings similar to
```
In file included from /usr/include/glib-2.0/gobject/gobject.h:24:0,
from /usr/include/glib-2.0/gobject/gbinding.h:29,
from /usr/include/glib-2.0/glib-object.h:23,
from cinnamon-settings-manager.c:30:
cinnamon-settings-manager.c:76:41: warning: redundant redeclaration of 'cinnamon_settings_manager_init' [-Wredundant-decls]
G_DEFINE_TYPE (CinnamonSettingsManager, cinnamon_settings_manager, G_TYPE_OBJECT)
^
/usr/include/glib-2.0/gobject/gtype.h:1943:17: note: in definition of macro '_G_DEFINE_TYPE_EXTENDED_BEGIN'
static void     type_name##_init              (TypeName        *self); \
^~~~~~~~~
/usr/include/glib-2.0/gobject/gtype.h:1590:43: note: in expansion of macro 'G_DEFINE_TYPE_EXTENDED'
#define G_DEFINE_TYPE(TN, t_n, T_P)       G_DEFINE_TYPE_EXTENDED …
```
> Fix redundant redeclarations

- plugins/datetime/csd-datetime-mechanism-main.c
- plugins/datetime/test-system-timezone.c
- plugins/power/csd-backlight-helper.c
- plugins/print-notifications/csd-printer.c
- plugins/smartcard/csd-smartcard-manager.c
- plugins/xsettings/fontconfig-monitor.c
- plugins/xsettings/test-gtk-modules.c
Based on https://git.gnome.org/browse/gnome-settings-daemon/commit/?id=1bb777166c3f52baa9af00c403fa8b3c23e6028f
> Remove calls to g_type_init(), bump GLib required version

- plugins/datetime/csd-datetime-mechanism-main.c
fixes
```
csd-datetime-mechanism-main.c:134:17: warning: 'g_thread_init' is deprecated [-Wdeprecated-declarations]
g_thread_init (NULL);
```
> remove deprecated g_thread_init

- plugins/mouse/csd-locate-pointer.c
the shadowed declarations of 'data' appear to be deliberate and fundamental to the
way this works, so have not been changed.
> csd-locate-pointer: change a shadowed variable causing compiler warnings

- plugins/clipboard/csd-clipboard-manager.c
There was actually a potential error here, the variables used for the clipboard max were larger than
those used to handle internal loops, so very large copies could have failed
if the maximum sizes were set very high.  There was also some very confusing variable
shadowing at one place.
> csd-clipboard-manager: remove compiler warnings

- plugins/media-keys/csd-media-keys-manager.c
When support was added to show this OSD the wrong values were being passed which
results in the a level bar showing in the OSD. Fix the values so we don't see it
anymore.
> media-keys: Don't show the level in the screen lock OSD

- plugins/xrandr/csd-xrandr-manager.c
Based on https://git.gnome.org/browse/gnome-settings-daemon/commit/?id=5f7643800a8bc26bd2835dc9a3df085bf0fab422
Each potential monitor configuration that can be cycled through with fn-f7 on laptops is generated by copying and tweaking the current monitor configuration. One necessary, but neglected tweak, was the current "clone" state. This means the clone state of the current configuration leaks into every other config. Users who start in a cloned mode can never leave a clone with the hotkey. This commit explicitly sets the clone state appropriately. Patch based on valuable, and detailed feedback provided by Marico Xu.
https://bugzilla.gnome.org/show_bug.cgi?id=677472
> xrandr: explicitly set clone state variable when generating monitor configs

- plugins/automount/csd-autorun.c
No real functionality change. Just set a default width and clean up some deprecations.
Some of the indentation looks a bit strange in diff shown here. I assume this is due to the original code using Tab:8 and the new using Spaces:8
> Clean up the autorun dialog a bit

- plugins/xsettings/csd-xsettings-gtk.c
If the GTK MODULES DIRECTORY does not open then a GFile would leak, this avoids that.
> csd-xsettings-gtk: Avoid a potential GFile leak

- plugins/housekeeping/csd-disk-space.c
https://github.com/GNOME/gnome-settings-daemon/commit/a7b82826bd716e50fae6668561117dfedc8873ec#diff-35dd745f84c1c68f9626401cda5ee45d
and one more minor removal of a duplicated call
> housekeeping: Fix deprecated GUnixMountMonitor calls

- plugins/media-keys/csd-media-keys-manager.c
It appears that cinnamon-settings-daemon tries to run
gnome-power-statistics via its .desktop file. However, it is using the
old .desktop filename, gnome-power-statistics.desktop, which changed
to org.gnome.PowerStats in GNOME 3.22; so I don't think this has worked
since before stretch.
This was originally reported to the Debian bug tracker[1] by Simon McVittie
[1]: https://bugs.debian.org/895481
> Update gnome-power-manager's stats desktop name

- data/org.cinnamon.settings-daemon.plugins.power.gschema.xml.in.in
- plugins/power/csd-power-manager.c
Closes #141.
Depends on https://github.com/linuxmint/cinnamon-desktop/pull/105
> Add an option to prevent handle-lid-switch from being inhibited. 

- plugins/housekeeping/csd-disk-space.c
This fixes the build with glib 2.57.2 (as seen in Ubuntu 18.10 "cosmic). See https://bugs.debian.org/905657
The build still works with glib 2.56 as tested with Debian unstable.
Commit message
----------------------
notify_notification_close() expects that a parameter will be available for
the error location, which could be a dangling pointer in a register or
on the stack in the case of some architectures.
This was caught by GNOME/glib#1425 which allows us to check proper type
parameters.
Cherry-picked to cinnamon-settings-daemon from
https://gitlab.gnome.org/GNOME/gnome-settings-daemon/commit/3110457f
> fix build with glib 2.57.2

- plugins/power/gpm-common.c
Not sure if this occurs with all types of gaming inputs, but seems consistent with a DualShock 4.
> Prevent log flooding when game controllers are detected

- plugins/media-keys/csd-media-keys-manager.c
* Removes if-elif-else ladder that determines which calculator application to open when XF86Calculator is pressed
* Instead, when XF86Calculator is pressed, CSD executes the command listed in the default calculator application schema (defined in commit [5b9ca20](https://github.com/linuxmint/cinnamon-desktop/commit/5b9ca2075dcfa9a23bdc9542cac90e6fc7252086) for [linuxmint/cinnamon-desktop](https://github.com/linuxmint/cinnamon-desktop))
* In order to function properly, this PR is dependent on the merger of commit 5b9ca20 into [linuxmint/cinnamon-desktop:master](https://github.com/linuxmint/cinnamon-desktop/tree/master) to define the schema
* I highly recommend merging commit [7879ac2](https://github.com/linuxmint/Cinnamon/commit/7879ac2dceeaeb6560e9277b1546154fb29b0b3d) into …
> csd-media-keys-manager.c: Honor default calculator application schema

- plugins/common/csd-power-helper.c
- plugins/common/csd-power-helper.h
- plugins/media-keys/csd-media-keys-manager.c
- plugins/power/csd-power-manager.c
Currently, if not using systemd, UPower < 0.99 is required to suspend or hibernate. This patch implements suspend/hibernate/hybrid sleep with ConsoleKit. It has been tested on Slackware 14.2 with UPower 0.99.7 and ConsoleKit2 1.0.0.
> Implement suspend/hibernate with ConsoleKit

- plugins/power/csd-backlight-helper.c
Fix a segmentation fault when no "-b" or "--backlight-preference" option is specified on the command line.
> Prevent Segmentation Fault

- plugins/media-keys/csd-media-keys-manager.c
The method was there all along
Fixes https://github.com/linuxmint/mint19.2-beta/issues/26
>  Fix Shutdown immediately not working - the easy way

- cinnamon-settings-daemon/cinnamon-settings-session.c
- plugins/common/csd-power-helper.c
ls /run/systemd/system/ returns nothing here
ls /run/systemd/seats
seat0
Based on https://github.com/linuxmint/cinnamon-session/commit/82b0cd50a046e6fa266ba93e549b66787f899c75
> Restore old check for logind

- plugins/automount/csd-automount-manager.c
- plugins/power/csd-power-manager.c
When a custom screensaver command is configured:
* Don't trigger cinnamon-screensaver
* Execute the custom screensaver command instead
* Pass the logind suspend inhibitor FD to the custom screensaver process
via environment variable XSS_SLEEP_LOCK_FD which is already supported
by a bunch of other screensavers. Those screensavers close the FD to
notify logind that the screen is fully locked and it's okay to suspend
now.
* Pass environment variable LOCKED_BY_SESSION_IDLE with either "true" or
"false" to the custom screensaver process so it can optionally dim the
screen before locking. Assume a dimming time of 10 seconds here, same
as hardcoded SCREENSAVER_FADE_TIME which cinnamon-screensaver also
uses.
This patch needs accompanying patches to cinnamon-desktop and cinnamon-screensaver …
> Handle a custom screensaver command

- configure.ac
- data/Makefile.am
- data/org.freedesktop.IBus.service.in
- debian/cinnamon-settings-daemon.install
- debian/cinnamon-settings-daemon.maintscript
- plugins/datetime/Makefile.am
In commit 139c7137525ab29ddfc4a6abfd6287cd3f626c22 the datetime plugin was (re)added to the tree, but the checks designed to control where the dbus files were placed, never did anything.
Make this work, and also change the default location of system.d to be more consistent with the services directory, i.e. in the datadir which is typically reserved for packaged software.
> Fix up the configure check for dbus directories.

- configure.ac
- plugins/Makefile.am
We lost a Cinnamon maintainer in Gentoo and it was almost removed from the Portage tree due to being unmaintained for a while. We got new one now, however I would like to backport some patches from Gentoo for ease of maintenance and support if such thing ever happen in the future. Thanks in advance for your cooperation.
Two things are done with this PR:
- Make colord, Wacom, logind optional configurable dependencies
- Fix smartcards check to require NSS if configure flag is explicitly enabled
> Modify build system to make some dependencies optional and fix some required dependencies

- plugins/power/Makefile.am
Some of the header files are generated using the `gdbus-codegen` tool, namely `csd-power-proxy.h`, `csd-power-screen-proxy.h` and `csd-power-keyboard-proxy.h`. There are rules to specify source files that depend on these headers, however `csd-power-manager.c` depends on all three of them and is not specified as a dependent source file. This leads to race condition on highly parallelized builds, where the source file compilation would be attempted before the headers are generated, leading to errors like:
```
csd-power-manager.c:50:10: fatal error: csd-power-proxy.h: No such file or directory
#include "csd-power-proxy.h"
^~~~~~~~~~~~~~~~~~~
compilation terminated.
```
fixes #248
> Fix the build in highly-concurrent scenarios

- plugins/automount/csd-automount-manager.c
This can be a race condition with nemo trying to load the location before gvfs finished initializing it.
> csd-automount-manager.c: Add a small delay to folder opening after a mount.

- plugins/a11y-keyboard/meson.build
- plugins/a11y-settings/meson.build
- plugins/automount/meson.build
- plugins/background/meson.build
- plugins/clipboard/meson.build
- plugins/color/meson.build
- plugins/common/meson.build
- plugins/cursor/meson.build
- plugins/datetime/meson.build
- plugins/housekeeping/meson.build
- plugins/keyboard/meson.build
- plugins/media-keys/meson.build
- plugins/mouse/meson.build
- plugins/orientation/meson.build
- plugins/power/meson.build
- plugins/print-notifications/meson.build
- plugins/screensaver-proxy/meson.build
- plugins/smartcard/meson.build
- plugins/sound/meson.build
- plugins/wacom/meson.build
- plugins/xrandr/meson.build
- plugins/xsettings/meson.build
commit 67d8cc67f666b726c2d76b6c1c6eb1dcc4cc53cc tries to ensure the programs are available from multiple locations, because users might have custom desktop files with broken paths. Unfortunately it does so by unconditionally deleting one of those locations!
This is exceedingly problematic on distros that do not use the lib vs. libexec split, because libexecdir == pkglibdir, hence the install script first deletes the program itself, then creates a symlink pointing to itself.
```
$ tree pkg/usr/lib/cinnamon-settings-daemon
pkg/usr/lib/cinnamon-settings-daemon
├── csd-a11y-keyboard -> csd-a11y-keyboard
├── csd-a11y-settings -> csd-a11y-settings
├── csd-automount -> csd-automount
├── csd-background -> csd-background
├── csd-backlight-helper -> csd-backlight-helper
├── csd-clipboard -> …
```
> do not delete programs and replace them with broken symlinks to themselves

- plugins/power/gpm-common.c
Fixes linuxmint/cinnamon#9823
Todo: Look at cinnamon power applet's handling of critical/warning level colors.
> power/gpm-common.c: Prefer more specific battery level icons if they're available in the theme.

- plugins/datetime/org.cinnamon.SettingsDaemon.DateTimeMechanism.service.in
Commit 0030d519, perhaps erroneously switched this path to be relative
to PATH instead of absolute, which results in an error when trying to
contact the service from cinnamon-settings:
```
Loading Calendar module
using csd backend
Traceback (most recent call last):
File "/usr/share/cinnamon/cinnamon-settings/modules/cs_calendar.py", line 175, in _on_proxy_ready
self._proxy = Gio.DBusProxy.new_for_bus_finish(result)
gi.repository.GLib.Error: g-dbus-error-quark: Error calling StartServiceByName for org.cinnamon.SettingsDaemon.DateTimeMechanism: Cannot launch daemon, file not found or permissions invalid (23)
```
Alongside an error from dbus-daemon:
```
Feb 23 12:46:32 suika dbus-daemon[1292]: [system] Activating service name='org.cinnamon.SettingsDaemon.DateTimeMechanism' requested by …
```
> datetime: use full path for d-bus service Exec

- meson.build
- meson_options.txt
- plugins/meson.build
- plugins/xrandr/meson.build
* Add missing `HAVE_NEW_LCMS` and `HAVE_WACOM` defines.
* Add build option for wacom dependency.
* Add missing `wacom` dependency to `xrandr` plugin.
* Make build options behave consistently.
> Meson build fixes

- plugins/wacom/csd-wacom-device.c
If the device stylus isn't recognized from the wacom kernel module it 
will just crash the module.
The real fix is to update the kernel and (maybe) prevent it from 
crashing wacom. This would leave the tablet in an undefined state.
Closes:
https://github.com/linuxmint/cinnamon-settings-daemon/issues/332
-------------------------------------------------------
what the heck happened in #334, i just force-pushed and it closed
> [Needs Testing] wacom: Fix a crashes from assertion failures (re-pr)

- meson.build
Just do one dependency() check but check the version result.
> meson: simplify version check for lcms2

- plugins/color/gcm-edid.c
Based on https://github.com/GNOME/gnome-settings-daemon/commit/7935a97354a950077d95655453b604669155c457
and https://github.com/GNOME/gnome-settings-daemon/commit/d948c8caf3dee1652e8ed05016a1b306dfa0fdf7
> EDID strings can be up to 13 bytes

- debian/cinnamon-settings-daemon.install
- debian/control
- debian/copyright
- debian/rules
merge some improvements from debian packages
> [muffin-5.2-test] debian packaging improvements

- plugins/media-keys/csd-media-keys-manager.c
On VOLUME_UP key press, we want to snap volume up to the nearest 5% step. Currently, volume snaps to the lower 5% step by integer division. Compare with VOLUME_DOWN code
Reports describing the bug:
https://github.com/linuxmint/cinnamon/issues/10048
https://github.com/linuxmint/cinnamon/issues/10269
> csd-media-keys-manager.c: Fix volume level 5% snap

- plugins/wacom/meson.build
The wacom uses the wrong rpath.
chrpath -l  csd-wacom*
csd-wacom: RUNPATH=lib/x86_64-linux-gnu/cinnamon-settings-daemon
csd-wacom-led-helper: RUNPATH=lib/x86_64-linux-gnu/cinnamon-settings-daemon
csd-wacom-oled-helper: RUNPATH=lib/x86_64-linux-gnu/cinnamon-settings-daemon
It should use  RUNPATH=/usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon-3.0
> Fix broken rpath

- plugins/power/gpm-idletime.c
alarm_item called after g_free = uaf, so free
the pointer array first and then the rest
> power: Fix free order

- meson.build
In NixOS packages are installed to their own separate prefix (i.e. `/nix/store/3srl963wzvfm3q3mnbnvrgz34yd93y7q-cinnamon-settings-daemon-5.6.1/share/icons/hicolor` instead of `/usr/share/icons/hicolor`), we don't have permission to write things to `/` in build time (we actually don't have `/usr/share`) :disappointed: 
```
[0/1] Installing files.
Installing subdir /build/source/files to /
Installation failed due to insufficient permissions.
Attempting to use polkit to gain elevated privileges...
pkexec must be setuid root
FAILED: meson-internal__install
/nix/store/754p0izaawcr1v28i0k3xbbj2r3m27n2-meson-0.64.1/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
```
https://github.com/NixOS/nixpkgs/blob/4106c75/pkgs/desktops/cinnamon/cinnamon-settings-daemon/use-sane-insta …
> build: don't hardcode files install dir as /

- data/org.cinnamon.settings-daemon.plugins.power.gschema.xml.in.in
- plugins/power/csd-power-manager.c
hi,
this is a long requested feature for gnome shell and cinnamon. there are too many posts asking how to disable low battery notifications, and someone even made some scripts that patch and recompile upower for gnome (works for gnome only; cinnamon is too different in this regard).
the problem is that many devices report low battery when they will be able to work fine for a long time, spamming the user with notifications. this happens a lot when users replace alkaline (1.5V nominal) batteries with nickel-based batteries (1.2V nominal). the lower voltage of the rechargeable batteries trigger the warning, but the devices typically work fine with just 1V or less.
this is a quick fix for keyboards and mice, which represent 99+ % of the issue i guess, with a coarse fix for the outliers if …
> power: Add settings to disable low battery warnings for connected devices

- plugins/wacom/csd-wacom-manager.c
Regression in commit 88e9de536db46ed1bda3777d24e9305d694099c6. This was probably a bad merge from gnome. The HAVE_WAYLAND define is never defined, but if it did then the code would try to include a cinnamon header that has never existed, then call a gnome-settings-daemon internal function that does not exist.
It is possible to properly implement HAVE_WAYLAND, but this code didn't.
> csd-wacom: remove ifdef code that cannot compile

- plugins/media-keys/csd-media-keys-manager.c
https://github.com/GNOME/gnome-settings-daemon/commit/332836c15337b10d2385ef987a9b400b6ba39a0a#diff-fcb794dabdef1a8bb7b756d63b4cfef764ff1dc8e9c6ae1758658dccec94cfa0R2919
> media-keys: Add support for an audio device selection dialog

- plugins/keyboard/csd-input-sources-switcher.c
- plugins/power/csd-backlight-helper.c
- plugins/power/csd-power-manager.c
Initially I wanted to fix typo only in assertion message like
"Attempting to call gsb-backlight-helper on non-Linux"
Note gsb instead of gsd here as well.
But later I decided to change it everywhere.
> Cosmetic change: rename g-s-d to c-s-d

- plugins/media-keys/csd-media-keys-manager.c
This allows us to show labels on the Cinnamon OSD's to get the look that we want.
> media-keys: Add labels for show_osd()

- meson_options.txt
- plugins/color/generate-tz-header.py
- plugins/color/meson.build
Allow distros to optionally re-generate the `tz-coords.h` header, on build, with their packaged version of timezone-data/tzdata.
I would have updated the csd-night-light code to dynamically parse the zone db, but I haven't done anything significant in C for quite some time.
This is a happy medium, which will make it easier for Gentoo to trigger a rebuild of cinnamon-settings-daemon whenever the zone db gets updated.
> Add option to generate tz-coords.h as part of the build process.

- data/org.cinnamon.settings-daemon.plugins.color.gschema.xml.in.in
- plugins/color/csd-night-light.c
This is more user-friendly than having to tweak the start and stop times.
Please see:
https://github.com/linuxmint/cinnamon/pull/12660
> nightlight: Implement schedule mode 'always'
