linuxmint/cinnamon-settings-daemon

- plugins/media-keys/csd-media-keys-manager.c
This is dependent on this PR in libcinnamon desktop https://github.com/linuxmint/cinnamon-desktop/pull/53. In addition, the main issue for this is here https://github.com/linuxmint/Cinnamon/issues/4448
One issue I should point out is that the icon displayed when the microphone mute button is pressed is for a speaker. It would probably be nice to change this to a microphone at some point in time.
> Pressing the mic-mute button now toggles the microphone's mute status

- plugins/datetime/csd-datetime-mechanism.c
http://seclists.org/oss-sec/2015/q4/180
https://bugzilla.suse.com/show_bug.cgi?id=951830
and
https://bugzilla.redhat.com/show_bug.cgi?id=1276639
> csd-datetime forgets to authorize users

- plugins/xrandr/csd-xrandr-manager.c
> remove a couple of unused variables

- plugins/mouse/csd-mouse-manager.c
as per https://github.com/linuxmint/cinnamon-settings-daemon/pull/131#issuecomment-269718531
> mouse: add missing device closing

- data/org.cinnamon.settings-daemon.peripherals.gschema.xml.in.in
- plugins/mouse/csd-mouse-manager.c
Add a few new gsettings keys that will make manipulation of these settings
easier from cinnamon settings.
> mouse-plugin: Add new settings for mouse/touchpad

- po/fi.po
> Fix typo in Finnish translation

- plugins/power/csd-power-manager.c
The warning seems useless and causes log spam, see example below
```
(csd-power:1656): power-plugin-WARNING **: session inhibition not available, cinnamon-session is not available
(csd-power:1656): power-plugin-WARNING **: session inhibition not available, cinnamon-session is not available
(csd-power:1656): power-plugin-WARNING **: session inhibition not available, cinnamon-session is not available
(csd-power:1656): power-plugin-WARNING **: session inhibition not available, cinnamon-session is not available
(csd-power:1656): power-plugin-WARNING **: session inhibition not available, cinnamon-session is not available
(csd-power:1656): power-plugin-WARNING **: session inhibition not available, cinnamon-session is not available
(csd-power:1656): power-plugin-WARNING **: session inhibition …
```
> power: Remove spam from log

- plugins/print-notifications/csd-print-notifications-manager.c
- plugins/print-notifications/csd-print-notifications-manager.h
- plugins/print-notifications/csd-printer.c
Rebased to the latest git master dated 2017-03-28 | print-notifications: Don't init GTK+
> rebase print-notifications

- data/org.cinnamon.settings-daemon.peripherals.gschema.xml.in.in
- plugins/mouse/csd-mouse-manager.c
The back end changes for the pull request at Cinnamon. I'll keep this text short and add the full description & discussion there.
> Make touchpad settings compatible with libinput

- plugins/sound/csd-sound-manager.c
https://github.com/GNOME/gnome-settings-daemon/commit/c2b32ad0641d28d6804b09680e8df22bf9bb7d7c#diff-31cf6d77ac3a65f51fb5b982a18862e9
> sound: Remove empty constructor function

- plugins/sound/csd-sound-manager.c
https://github.com/GNOME/gnome-settings-daemon/commit/5af696b8740af7744a1b6566861ff688bd0f655e#diff-31cf6d77ac3a65f51fb5b982a18862e9
> sound: Don't include unused GTK+

- plugins/common/csd-keygrab.c
https://github.com/GNOME/gnome-settings-daemon/commit/4a164e0aa37917e52ac5526ca0d647bd5f7a393b#diff-2987e9ed8eee4afc13c6ba32d03d94fa
> common: add break and scroll lock to whitelist

- plugins/housekeeping/csd-ldsm-dialog.c
https://github.com/GNOME/gnome-settings-daemon/commit/92fc1c2f605561126e37dc9a69459d5ac66c1e90#diff-35dd745f84c1c68f9626401cda5ee45d
> housekeeping: replace gtk_stock items

- plugins/power/csd-power-manager.c
> Handle AC remove while LID is closed

- data/org.cinnamon.settings-daemon.peripherals.gschema.xml.in.in
- plugins/mouse/csd-mouse-manager.c
Adding natural scrolling for mouse using 2 different namespace for the setting
> Add natural-scroll support for mice

- plugins/automount/Makefile.am
- plugins/automount/csd-autorun.c
- plugins/automount/csd-autorun.h
- plugins/automount/test-automount-dialog.c
For debugging and testing the popup window itself.
> automount: Add autorun dialog tester.

- plugins/common/csd-power-helper.c
- plugins/common/csd-power-helper.h
- plugins/media-keys/csd-media-keys-manager.c
- plugins/power/csd-power-manager.c
This consists of 3 PRs (involved repositories: cinnamon, cinnamon-session, cinnamon-settings-daemon)
> add suspend-then-hibernate (issue #237)

- debian/control
- debian/rules
- debian/control: remove very old breaks
- debian/rules: enable hardening bindnow
> Improve deb

- plugins/automount/csd-autorun.c
- plugins/automount/csd-autorun.h
- plugins/automount/test-automount-dialog.c
- plugins/color/csd-color-manager.c
- plugins/datetime/csd-datetime-mechanism.c
- plugins/keyboard/csd-keyboard-xkb.c
- plugins/media-keys/csd-media-keys-manager.c
- plugins/power/gpm-common.c
Tested on actual hardware.
If you want I can try and recreate the commit without the whitespaces if it bothers you (Sometimes nano will remove it too)
> Shush compiler warnings

- data/org.cinnamon.settings-daemon.peripherals.gschema.xml.in.in
- plugins/common/csd-input-helper.c
- plugins/common/csd-input-helper.h
- plugins/mouse/csd-mouse-manager.c
Based on
https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/commit/d1d3eaf792b500b8579eef6a2e34a4a1682e11a8
https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/commit/4f30831e0176a775f00b7af86bd19c664a68bc5c
> Add trackball support

- plugins/media-keys/mpris-controller.c
Imported from upstream:
https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/merge_requests/87/diffs.
Fixes #331
> Fix MPRIS issues with disconnecting clients
